os: linux
services:
   - docker
sudo: required
language: python
env:
  global:
    - CONAN_REFERENCE="portaudio/v19.20140130"
    - CONAN_USERNAME="jgsogo"
    - CONAN_CHANNEL="stable"
    - CONAN_TOTAL_PAGES=1
    - CONAN_CURRENT_PAGE=1
    - CONAN_REMOTES="https://api.bintray.com/conan/jgsogo/conan-packages"
    - CONAN_UPLOAD="https://api.bintray.com/conan/jgsogo/conan-packages"

  matrix:
    - CONAN_GCC_VERSIONS=4.8 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.9 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.2 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.3 CONAN_USE_DOCKER=1
matrix:
   include:
       - os: osx
         osx_image: xcode7.3
         language: generic
         env:
       - os: osx
         osx_image: xcode7.1
         language: generic
         env:
       - os: osx
         osx_image: xcode8.1
         language: generic
         env:

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh

