#  PORTAUDIO_FOUND - system has libportaudio
#  PORTAUDIO_INCLUDE_DIRS - the libportaudio include directory
#  PORTAUDIO_LIBRARIES - Link these to use libportaudio

find_path(PORTAUDIO_INCLUDE_DIR NAMES portaudio.h PATHS ${CONAN_INCLUDE_DIRS_PORTAUDIO})
find_library(PORTAUDIO_LIBRARY NAMES ${CONAN_LIBS_PORTAUDIO} PATHS ${CONAN_LIB_DIRS_PORTAUDIO})

MESSAGE("** PORTAUDIO ALREADY FOUND BY CONAN!")
SET(PORTAUDIO_FOUND TRUE)
MESSAGE("** FOUND PORTAUDIO:  ${PORTAUDIO_LIBRARY}")
MESSAGE("** FOUND PORTAUDIO INCLUDE:  ${PORTAUDIO_INCLUDE_DIR}")

set(PORTAUDIO_INCLUDE_DIRS ${PORTAUDIO_INCLUDE_DIR})
set(PORTAUDIO_LIBRARIES ${PORTAUDIO_LIBRARY})

mark_as_advanced(PORTAUDIO_LIBRARY PORTAUDIO_INCLUDE_DIR)

